# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    identifier: 1eb98550
    url: /#news
    weight: 10
  - name: Projects
    identifier: 1134f0f5
    url: projects/
    weight: 20
  - name: Publications
    identifier: 84e4822c
    url: /#papers
    weight: 30
  - name: Experience
    identifier: a3e8a7f4
    url: experience/
    weight: 40
  - name: Teaching
    identifier: 299ce9fa
    url: /courses/
    weight: 50
  - name: Bio
    identifier: 60097c31
    url: /
    weight: 60
